In [1]:
import numpy as np

In [7]:
#arrays (table of numbers) with numpy
a = np.array([1,2,3,4])
print(type(a))
print(a.shape) #shapt funt gives rows, columns of the array
print(a[0], a[2], a[3])
a[0] = 7 #changes the variable for the number in the 1st position 
print(a)

<class 'numpy.ndarray'>
(4,)
1 3 4
[7 2 3 4]


In [11]:
#arrays with 2 rows and 3 columns
b = np.array([[5,6,7],[2,4,9]]) #rows rep the brackets and columns are in the commas
print(b.shape)
print(b[0,0], b[0,1], b[1,0])
print(b) #print array

(2, 3)
5 6 2
[[5 6 7]
 [2 4 9]]


In [31]:
#creating zero matrix
zeros_array = np.zeros((2,2)) #argument/ parameters are in parenthesis  
print(zeros_array)

ones_array = np.ones((3,2))
print(ones_array)

full_array = np.full((3,4),5) #array is 3x4 with an element of 5
print(full_array)

identity_array = np.eye(3) #identity is a square so only one parameter needs to be set 3x3
print(identity_array)

random_array_int = np.random.randint(100,150,(2,2))
print(random_array_int)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[143 100]
 [112 137]]


In [33]:
print(random_array_int[:,1]) #printing all elements from the seond column

print(random_array_int[1,:]) #print all elements from the second row

[100 137]
[112 137]
