In [1]:
import numpy as np

In [4]:
#create a square matrix

x = np.array([[1,5,6],[8,5,9],[1,0,3]])
z = np.array([[12,20,-3],[5,-8,5],[16,9,17]])
print(x, "\n")
print(z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [16  9 17]]


In [5]:
#subtract matrix x and z

r_added= x.__add__(z)
r_sub = x.__sub__(z)
print(r_added, "\n")
print(r_sub, "\n")

[[13 25  3]
 [13 -3 14]
 [17  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [-15  -9 -14]] 



In [6]:
#Piecewise mulitplication and mulitplication of two matrice

r_piecewise = x.__mul__(z)
r_mul = x.__mul__(z)
print(r_piecewise, "\n")
print(r_mul)

[[ 12 100 -18]
 [ 40 -40  45]
 [ 16   0  51]] 

[[ 12 100 -18]
 [ 40 -40  45]
 [ 16   0  51]]


In [9]:
# 1x+1y=2 and 10x+35y =30

A = np.array([[1,1],[10,35]])
b = np.array([[2],[30]])


In [11]:
#Verify hte size of matrix A and b

print("dim. of matrix A=", A.shape)
print("dim. of vector b=", b.shape)

dim. of matrix A= (2, 2)
dim. of vector b= (2, 1)


In [12]:
#find the det(A)  

np.linalg.det(A)

25.000000000000007

In [13]:
#finding the inverse 
inv_A = np.linalg.inv(A) #saved the data as a variable so we have to print the variable 
print(inv_A)

[[ 1.4  -0.04]
 [-0.4   0.04]]


In [15]:
#find the solution

sol = inv_A.dot(b)
print(sol)

[[1.6]
 [0.4]]


In [17]:
print(1*1.6+1*0.4)
print(10*1.6+35*0.4)

2.0
30.0
